### ISSUE TITLE
undefined Day of Week

### ISSUE THREAD

**Issue by horus1963** [joaquingatica/elvish-date#3]
Just noticed another problem. If you try to find the day of week name for 2018-01-12 you will get an undefined day of week name. This repeats every seven days. I guess the class presumes that the week has seven days in it and has no name for the seventh day after Valanya.

Thank you very much for the excellent work!

**Comment by horus1963** [comment]
Just a quick correction. It turns out that the week is still 6 days. Which is great! The only problem is that We are missing an entry for Elenya. So the week now is:

undefined, Anarya, Isilya, Aldúya, Menelya, Valanya

Hope this helps

**Comment by joaquingatica** [comment]
Ah nice catch! I'll take a look at this and push the fix. Thanks!

**Comment by joaquingatica** [comment]
@horus1963 Issue fixed in v1.0.2
